# -*- coding: utf-8 -*-
"""lab3_lemma_pos_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1814cY6o5fH8hbA48YjAw-nRZVD6dFSgo
"""

!pip install stanza scikit-learn

import pandas as pd
import stanza

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score

from google.colab import drive
drive.mount('/content/drive')
# download processed file to your drive

df_text = pd.read_csv('drive/MyDrive/Colab Notebooks/NLP/processed_v2.xls')
df_labels = pd.read_csv('drive/MyDrive/Colab Notebooks/NLP/labels.xls')

# assume labels file has single column
df_text["label"] = df_labels.iloc[:, 0]

df = df_text.dropna(subset=["statement_1", "statement_2", "label"])


df["pair_text"] = (
    df["statement_1"].astype(str) + " [SEP] " +
    df["statement_2"].astype(str)
)

stanza.download("uk")
nlp = stanza.Pipeline("uk", processors="tokenize,pos,lemma", use_gpu=False)

def lemmatize(text):
    doc = nlp(text)
    lemmas = []
    pos_tags = []

    for sent in doc.sentences:
        for word in sent.words:
            lemmas.append(word.lemma.lower())
            pos_tags.append(word.upos)

    return " ".join(lemmas), " ".join(pos_tags)

df[["lemma_text", "upos_seq"]] = df["pair_text"].apply(
    lambda x: pd.Series(lemmatize(x))
)

X_train_raw, X_test_raw, y_train, y_test = train_test_split(
    df["pair_text"],
    df["label"],
    test_size=0.2,
    random_state=42,
    stratify=df["label"]
)

X_train_lemma, X_test_lemma, _, _ = train_test_split(
    df["lemma_text"],
    df["label"],
    test_size=0.2,
    random_state=42,
    stratify=df["label"]
)

vectorizer_raw = TfidfVectorizer(ngram_range=(1,2), max_features=20000)

Xtr_raw = vectorizer_raw.fit_transform(X_train_raw)
Xte_raw = vectorizer_raw.transform(X_test_raw)

model_raw = LogisticRegression(max_iter=1000)
model_raw.fit(Xtr_raw, y_train)

pred_raw = model_raw.predict(Xte_raw)

print("Baseline 1 — raw")
print("Accuracy:", accuracy_score(y_test, pred_raw))
print("Macro-F1:", f1_score(y_test, pred_raw, average="macro"))

vectorizer_lemma = TfidfVectorizer(ngram_range=(1,2), max_features=20000)

Xtr_lemma = vectorizer_lemma.fit_transform(X_train_lemma)
Xte_lemma = vectorizer_lemma.transform(X_test_lemma)

model_lemma = LogisticRegression(max_iter=1000)
model_lemma.fit(Xtr_lemma, y_train)

pred_lemma = model_lemma.predict(Xte_lemma)

print("\nBaseline 2 — lemma")
print("Accuracy:", accuracy_score(y_test, pred_lemma))
print("Macro-F1:", f1_score(y_test, pred_lemma, average="macro"))

errors_idx = X_test_raw.index[pred_raw != y_test]

for i in errors_idx[:10]:
    print("="*50)
    print("Statement 1:", df.loc[i, "statement_1"])
    print("Statement 2:", df.loc[i, "statement_2"])
    print("True:", y_test.loc[i])
    print("Pred:", pred_raw[list(X_test_raw.index).index(i)])

    doc = nlp(df.loc[i, "pair_text"])

    for sent in doc.sentences:
        for word in sent.words:
            print(f"{word.text} | lemma: {word.lemma} | POS: {word.upos}")

    print("Comment: manual analysis")

"""У нашому експерименті використання lemma_text не дало суттєвого покращення baseline, а в частині випадків якість навіть знизилась. Зокрема, модель не змогла правильно визначити семантичну еквівалентність у парафразах типу «У мене є кіт» — «Я маю кота» або «Чому ти це зробив?» — «Нащо ти це зробив?», хоча леми формально збігалися частково. Також спостерігаються помилки лематизації та POS-тегування власних назв і окремих форм (наприклад, «Том» як NOUN замість PROPN), що потенційно впливає на якість ознак. Лематизація не допомогла у випадках синонімічних конструкцій («Бога немає» — «Бога не існує», «Я не заперечую» — «Я не проти»), оскільки TF-IDF не враховує глибинну семантику. Для нашого проєкту доцільно не використовувати леми як основне представлення для класифікації"""